server:
  port: 8083

spring:
  application:
    name: follow-service
  datasource:
    url: jdbc:postgresql://localhost:5432/follow_db
    username: connectsphere
    password: connectsphere
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

