server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:post_db}
    username: ${DB_USERNAME:connectsphere}
    password: ${DB_PASSWORD:connectsphere}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
