server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: feed-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

services:
  post-service-base-url: ${POST_SERVICE_BASE_URL:http://localhost:8082}
  follow-service-base-url: ${FOLLOW_SERVICE_BASE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
